### ISSUE TITLE
support `ssh-ed25519` keys

### ISSUE THREAD

**Issue by Schnitzel** [vshn/puppet-identity#12]
currently it is hardcoded to use `ssh-rsa` keys:
https://github.com/vshn/puppet-identity/blob/master/manifests/user.pp#L184

but would be great to also support ED25519, see http://security.stackexchange.com/questions/5096/rsa-vs-dsa-for-ssh-authentication-keys/46781#46781

**Comment by Schnitzel** [comment]
pinging @tobru here :)

**Comment by maetthu-indermuehle** [comment]
Hi @Schnitzel 

You can already use ED25519 without a problem:

```
users:
  user1:
    comment: 'user1'
    ssh_keys:
      main:
        type: 'ssh-ed25519'
        key: 'AAAAAblalbademo'
```

The line you reference is only a default value that can be overwritten.
