### ISSUE TITLE
'type' => 'ssh-rsa' is hard coded

### ISSUE THREAD

**Issue by ingardm** [vshn/puppet-identity#4]
Should be a parameter to allow for different types of keys

**Comment by andrekeller** [comment]
Hi,

it is not, you can specifiy type => ssh-dss if you want a DSA key f.e.

```
users:
  test.user:
    ensure: present
    uid: 2001
    comment: 'Test User'
    password: 'pwhash'
    ssh_keys:
      main:
        key: 'thekey'
        type: 'ssh-dss'
```
